### ISSUE TITLE
Erro na execução

### ISSUE THREAD

**Issue by DennysMuller** [wlsf82/backstop-config#3]
**Describe the bug**
Após fazer a conf. da aplicação (https://www.udemy.com/course/testes-de-regressao-visual-com-backstopjs/learn/lecture/18837182#overview) ocorre o erro na execução do teste.

**To Reproduce**
1. npm t
2. enter

**Expected behavior**
Inciar os testes

**Screenshots**
![image](https://user-images.githubusercontent.com/62710068/82607490-46486680-9b8f-11ea-976d-5a1c73982f4f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro Versão 1909 (Compilação do SO 18363.836)
 - Browser: Chrome Versão 81.0.4044.138 (Versão oficial) 64 bits

**Additional context**
LOG

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\dennys.benevides\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'backstop:test'
1 verbose cli ]
2 info using npm@6.11.3
3 info using node@v12.16.3
4 verbose run-script [ 'prebackstop:test', 'backstop:test', 'postbackstop:test' ]
5 info lifecycle backstop-config@1.0.0~prebackstop:test: backstop-config@1.0.0
6 info lifecycle backstop-config@1.0.0~backstop:test: backstop-config@1.0.0
7 verbose lifecycle backstop-config@1.0.0~backstop:test: unsafe-perm in lifecycle true
8 verbose lifecycle backstop-config@1.0.0~backstop:test: PATH: C:\Users\dennys.benevides\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;P:\backstop-config\node_modules\.bin;C:\Users\dennys.benevides\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;P:\backstop-config\node_modules\.bin;P:\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;P:\bin;C:\DEV\Python\Scripts;G:\Meu Drive\Aplicativos_Teste\Ggatling\bin;C:\DEV\Python;C:\DEV\Python\Scripts;C:\Program Files\Java\jdk1.8.0_191\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\Skype\Phone;C:\DEV\Teste\Infra\maven\bin;C:\DEV\Teste\Infra;C:\Program Files\Git\cmd;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\DEV\Python\Scripts;C:\DEV\Python;C:\Users\dennys.benevides\AppData\Local\Microsoft\WindowsApps;C:\Users\dennys.benevides\AppData\Local\JetBrains\DataGrip 2019.3.3\bin;C:\Users\dennys.benevides\AppData\Roaming\npm;C:\Users\dennys.benevides\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle backstop-config@1.0.0~backstop:test: CWD: P:\backstop-config
10 silly lifecycle backstop-config@1.0.0~backstop:test: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'npm run clean:bitmaps_test && backstop test --config=test/mainConfig.js'
10 silly lifecycle ]
11 silly lifecycle backstop-config@1.0.0~backstop:test: Returned: code: 2  signal: null
12 info lifecycle backstop-config@1.0.0~backstop:test: Failed to exec backstop:test script
13 verbose stack Error: backstop-config@1.0.0 backstop:test: `npm run clean:bitmaps_test && backstop test --config=test/mainConfig.js`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\dennys.benevides\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\dennys.benevides\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid backstop-config@1.0.0
15 verbose cwd P:\backstop-config
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dennys.benevides\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "backstop:test"
18 verbose node v12.16.3
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 2
22 error backstop-config@1.0.0 backstop:test: `npm run clean:bitmaps_test && backstop test --config=test/mainConfig.js`
22 error Exit status 2
23 error Failed at the backstop-config@1.0.0 backstop:test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
@wlsf82

**Comment by PauloGoncalvesBH** [comment]
@DennysMuller 
Acessa o seu arquivo `package.json` e cola aqui toda a seção `scripts`.

Acredito que o seu script `clean:bitmap_test` está com o valor:
`rmdir /S /Q test\backstop_data\bitmaps_test`
com isso está tentando excluir o diretório `bitmaps_test`, porém está quebrando por não encontrá-lo.

Como você está usando o git bash, você pode alterá-lo para:
`"clean:bitmaps_test": "rm -rf test/backstop_data/bitmaps_test",`

Com isso tenta excluir o diretório, se não encontrar não ocorre erro. Esse comando é para linux.

**Comment by DennysMuller** [comment]
Muitíssimo obrigado @PauloGoncalvesBH
