### ISSUE TITLE
Running scenarios in batches?

### ISSUE THREAD

**Issue by DanielStoica85** [wlsf82/backstop-config#6]
Hi, 

This is not a bug report or a feature request, I just have a question.

I am trying to use this framework while having a pretty high number of pages to test (around 500). This usually doesn't work, the process crashes when running the comparison script. Is there a way to maybe run this in batches of 100 scenarios at a time, for example? 

Thanks in advance!

**Comment by wlsf82** [comment]
Hi @DanielStoica85, thanks for your question!

This [blog post](https://medium.com/@fedevegili/the-power-of-serverless-visual-regression-tests-from-20-minutes-to-10-seconds-bc47b2ce9d20) and repositories (https://github.com/fedevegili/serverless-backstopjs-runner and https://github.com/fedevegili/serverless-backstopjs) might be helpful to your needs.

Let me know what do you think.

**Comment by DanielStoica85** [comment]
Hey @wlsf82 ,

Thanks for the quick reply.

I am not sure if we can apply that solution, since we don't use AWS. 

If you have any other ideas, please let me know, I would appreciate it.

**Comment by wlsf82** [comment]
> Hey @wlsf82 ,
> 
> Thanks for the quick reply.
> 
> I am not sure if we can apply that solution, since we don't use AWS.
> 
> If you have any other ideas, please let me know, I would appreciate it.

I don't have any other ideas at the moment, sorry.

I'm closing the issue.
